### ISSUE TITLE
Track lines @ 1:144,448

### ISSUE THREAD

**Issue by emilyebba** [vannizhang/hurricane#21]
Hi,

Can we add the track lines in at 1:144,448 scale?  For now with a .50 white line?  

Curious, is it possible to have the track highlight in yellow, as well as the yellow dot, at this scale when the user clicks on it?  This might look bad, but I thought I would ask first.

Thanks,

EM

**Comment by vannizhang** [comment]
@emilyebba You can make those style changes in the web map, right? I would make sure make the changes to the dev version of the web map first before making nay changes to the production web map.

**Comment by emilyebba** [comment]
Will do.  I was not sure if you wanted to control this like you are for the forecast symbols.  But yes.  I will add it to the clone version.  Thank you.

**Comment by vannizhang** [comment]
@emilyebba The forecast symbols layer is an exception...I would try to not touch the map and layers whenever possible because you own that part. Please send me the item id of the clone version of the web map so I can update the app to have the DEV app point to it.
